# Generated by Django 2.1.7 on 2020-08-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('noofchallengessolved', models.IntegerField()),
                ('expertiselevel', models.IntegerField()),
                ('datastructure', models.IntegerField()),
                ('algo', models.IntegerField()),
                ('cpp', models.IntegerField()),
                ('java', models.IntegerField()),
                ('python', models.IntegerField()),
                ('vote', models.IntegerField()),
            ],
        ),
    ]
